# Vendor C: Custom Platform (Asian Market)

In [0]:
# IMPORT STATEMENT
from pyspark.sql.functions import (
    input_file_name, current_timestamp, lit, col, when, coalesce, from_json, regexp_replace
)

## Preparing Bronze Schema

In [0]:
%sql
CREATE CATALOG IF NOT EXISTS fixing_the_broken_data_pipeline;
USE CATALOG fixing_the_broken_data_pipeline;
CREATE SCHEMA IF NOT EXISTS bronze;

In [0]:
# COMMON VARIABLES
bucket = "vendor-data-24042026"
vendor_data_dir = "vendor_c_customplatform_data"
target_table = "bronze.orders_vendor_c_customplatform"

records = "orders_*.tsv"
path = f"s3a://{bucket}/{vendor_data_dir}/{records}"

In [0]:
# READING THE DATA
df_raw = (
    spark.read
    .options(header=True, delimiter='\t', inferSchema=True)
    .csv(f"{path}")
)

df_raw.toPandas().head(5)

  order_number  ... device_type
0      C916233  ...     desktop
1      C912516  ...      mobile
2      C917823  ...     desktop
3      C909214  ...      tablet
4      C916674  ...      mobile

[5 rows x 6 columns]

In [0]:
# REMOVING THE QUOTES
df_raw = (
    spark.read
    .options(header=True, delimiter='\t', inferSchema=True, quote = '"', escape = '"')
    .csv(f"{path}")
)

df_raw.toPandas().head(5)

  order_number  ... device_type
0      C916233  ...     desktop
1      C912516  ...      mobile
2      C917823  ...     desktop
3      C909214  ...      tablet
4      C916674  ...      mobile

[5 rows x 6 columns]

In [0]:
df_bronze = (
    df_raw
        .withColumn("_source_file", col("_metadata.file_path"))
        .withColumn("_ingestion_timestamp", current_timestamp())
        .withColumn("_source_vendor", lit("Vendor A"))
)

# SAVING INTO DELTA FORMAT
df_bronze.write.format("delta").mode("append").option("mergeSchema", "true").saveAsTable(target_table)

# CHECKING
df_bronze.toPandas().head(5)

  order_number          created_at  ...       _ingestion_timestamp _source_vendor
0      C916233 2025-03-28 11:10:09  ... 2026-05-01 01:50:23.965661       Vendor A
1      C912516 2025-03-28 06:30:35  ... 2026-05-01 01:50:23.965661       Vendor A
2      C917823 2025-03-28 17:50:58  ... 2026-05-01 01:50:23.965661       Vendor A
3      C909214 2025-03-28 18:15:09  ... 2026-05-01 01:50:23.965661       Vendor A
4      C916674 2025-03-28 05:15:00  ... 2026-05-01 01:50:23.965661       Vendor A

[5 rows x 9 columns]

In [0]:
%sql
DESC bronze.orders_vendor_b_magento_data

col_name,data_type,comment
order_id,string,null
order_date,date,null
customer_email,string,null
product_code,string,null
quantity,int,null
unit_price,string,null
total_amount,string,null
payment_method,string,null
country_code,string,null
vat_rate,string,null
vat_amount,string,null
_source_file,string,null
_ingestion_timestamp,timestamp,null
_source_vendor,string,null